name: Deploy docker images

on:
  workflow_dispatch: 

jobs:
  build-scratch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy scratch image
        run: |
          docker build --target agent-scratch -t agent-scratch -f src/agent/Dockerfile src/agent
          docker login -u coderookieerick -p ${{ secrets.DOCKER_HUB }}
          docker tag agent-scratch coderookieerick/attoci:agent-scratch
          docker push coderookieerick/attoci:agent-scratch

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy alpine image
        run: |
          docker build --target agent-alpine -t agent-alpine -f src/agent/Dockerfile src/agent
          docker login -u coderookieerick -p ${{ secrets.DOCKER_HUB }}
          docker tag agent-alpine coderookieerick/attoci:agent-alpine
          docker push coderookieerick/attoci:agent-alpine

  build-golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy golang image
        run: |
          docker build --target agent-golang -t agent-golang -f src/agent/Dockerfile src/agent
          docker login -u coderookieerick -p ${{ secrets.DOCKER_HUB }}
          docker tag agent-golang coderookieerick/attoci:agent-golang
          docker push coderookieerick/attoci:agent-golang

  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy python image
        run: |
          docker build --target agent-python -t agent-python -f src/agent/Dockerfile src/agent
          docker login -u coderookieerick -p ${{ secrets.DOCKER_HUB }}
          docker tag agent-python coderookieerick/attoci:agent-python
          docker push coderookieerick/attoci:agent-python

  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy node image
        run: |
          docker build --target agent-node -t agent-node -f src/agent/Dockerfile src/agent
          docker login -u coderookieerick -p ${{ secrets.DOCKER_HUB }}
          docker tag agent-node coderookieerick/attoci:agent-node
          docker push coderookieerick/attoci:agent-node